import "./SchoolInfo.css";

function SchoolInfo(props) {
  console.log(props.School);

  return (
    <>
      <table>
        <tr>
          <th>Name</th>
          <th>Age</th>
          <th>School</th>
          <th>Class</th>
          <th>ClassId</th>
          <th>Section</th>
          <th>City</th>
          <th>TeacherName</th>
        </tr>
        <tr>
          <td>{props.School.student1.name}</td>
          <td>{props.School.student1.age}</td>
          <td>{props.School.student1.school}</td>
          <td>{props.School.student1.class}</td>
          <td>{props.School.student1.classId}</td>
          <td>{props.School.student1.section}</td>
          <td>{props.School.student1.city}</td>
          <td>{props.School.student1.teacherName}</td>
        </tr>
        <tr>
          <td>{props.School.student2.name}</td>
          <td>{props.School.student2.age}</td>
          <td>{props.School.student2.school}</td>
          <td>{props.School.student2.class}</td>
          <td>{props.School.student2.classId}</td>
          <td>{props.School.student2.section}</td>
          <td>{props.School.student2.city}</td>
          <td>{props.School.student2.teacherName}</td>
        </tr>
        <tr>
          <td>{props.School.student3.name}</td>
          <td>{props.School.student3.age}</td>
          <td>{props.School.student3.school}</td>
          <td>{props.School.student3.class}</td>
          <td>{props.School.student3.classId}</td>
          <td>{props.School.student3.section}</td>
          <td>{props.School.student3.city}</td>
          <td>{props.School.student3.teacherName}</td>
        </tr>
        <tr>
          <td>{props.School.student4.name}</td>
          <td>{props.School.student4.age}</td>
          <td>{props.School.student4.school}</td>
          <td>{props.School.student4.class}</td>
          <td>{props.School.student4.classId}</td>
          <td>{props.School.student4.section}</td>
          <td>{props.School.student4.city}</td>
          <td>{props.School.student4.teacherName}</td>
        </tr>
        <tr>
          <td>{props.School.student5.name}</td>
          <td>{props.School.student5.age}</td>
          <td>{props.School.student5.school}</td>
          <td>{props.School.student5.class}</td>
          <td>{props.School.student5.classId}</td>
          <td>{props.School.student5.section}</td>
          <td>{props.School.student5.city}</td>
          <td>{props.School.student5.teacherName}</td>
        </tr>
        <tr>
          <td>{props.School.student6.name}</td>
          <td>{props.School.student6.age}</td>
          <td>{props.School.student6.school}</td>
          <td>{props.School.student6.class}</td>
          <td>{props.School.student6.classId}</td>
          <td>{props.School.student6.section}</td>
          <td>{props.School.student6.city}</td>
          <td>{props.School.student6.teacherName}</td>
        </tr>
        <tr>
          <td>{props.School.student7.name}</td>
          <td>{props.School.student7.age}</td>
          <td>{props.School.student7.school}</td>
          <td>{props.School.student7.class}</td>
          <td>{props.School.student7.classId}</td>
          <td>{props.School.student7.section}</td>
          <td>{props.School.student7.city}</td>
          <td>{props.School.student7.teacherName}</td>
        </tr>
        <tr>
          <td>{props.School.student8.name}</td>
          <td>{props.School.student8.age}</td>
          <td>{props.School.student8.school}</td>
          <td>{props.School.student8.class}</td>
          <td>{props.School.student8.classId}</td>
          <td>{props.School.student8.section}</td>
          <td>{props.School.student8.city}</td>
          <td>{props.School.student8.teacherName}</td>
        </tr>
      </table>
    </>
  );
}

export default SchoolInfo;
